version: "3"

services:
  # Database
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: candylanddb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      # DB_CONNECTION=mysql
      # DB_HOST=mysql
      # DB_PORT=3306
      # DB_DATABASE=candyland_db
      # DB_USERNAME=root
      # DB_PASSWORD=password
      MYSQL_DATABASE: candyland_db
      MYSQL_HOST: db
      MYSQL_USER: Tamerap
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: Friday91!
    networks:
      - mysql-phpmyadmin
      
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: candyland_phpma
    restart: always
    ports:
      - "3306:3306"
      # - "8090:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: Friday91!
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data: